apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
  labels:
    app: zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
  - name: temp
    port: 9411
    protocol: "TCP"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
    fabric8.io/git-branch: "release-v0.1.5"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
    fabric8.io/build-id: "3"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
  labels:
    app: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
        fabric8.io/build-id: "3"
        fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
        fabric8.io/git-branch: "release-v0.1.5"
        fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      labels:
        app: zipkin
    spec:
      containers:
      - env:
        - name: COLLECTOR_KAFKA_ENABLED
          value: "true"
        - name: TRANSPORT_TYPE
          value: http
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: http://kafka-headless:9092
        - name: HTTP_COLLECTOR_ENABLED
          value: "true"
        - name: COLLECTOR_ACTIVEMQ_ENABLED
          value: "false"
        - name: COLLECTOR_RABBITMQ_ENABLED
          value: "false"
        - name: QUERY_LOG_LEVEL
          value: DEBUG
        - name: logging.level.zipkin2
          value: DEBUG
        - name: "KUBERNETES_NAMESPACE"
          value: default
        image: "openzipkin/zipkin:latest"
        name: zipkin
        ports:
        - name: temp
          containerPort: 9411
        readinessProbe:
          httpGet:
            path: /api/v1/services
            port: 9411
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 20
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
